### PR TITLE
Add ASP.NET Core 1.1 Benchmark

### LINKED ISSUE #17: ASP.NET Core
Would you accept a PR with a ASP.NET Core server?

### PR DESCRIPTION
**Pull request by kblok**
@costajob If you need a hand setting up the env just let me know. I followed the steps published here https://www.microsoft.com/net/core#macos in a brand new VM and It worked as expected.

Just as a reference, I was getting between 80k and 87k requests per second.

Closes #17

### CODE REVIEW

**Comment by costajob** [comment]
Thanks @kblok: i've added your .NET code to the benchmark. 
I've changed the README file to list the comparison by mentioning the C-Sharp language and by using the .NET Core as the platform.
Regarding benchmark i confirmed your numbers: my best lap was 84k req/sec, so within faster solutions.
Anyway consistency of .NET Core is worst than JVM based languages and far away from binary compiled ones (GO and Crystal).
I also recorded very high memory consumption: more than one gigabyte, surpassing memory-avid Scala by twice. Have you recorded similar results in memory consumption? I fear that it can be a cross platform issue of .NET Core and that it will be much better on MS Windows.
Regards!

**Comment by kblok** [comment]
@costajob yes I've got similar results here. I think asp.net performs better on linux. Check this out https://www.techempower.com/benchmarks/#section=data-r13&hw=ph&test=plaintext

**Comment by costajob** [comment]
Indeed by removing the thread limits from Program.cs i was able to squeeze some more throughput from Kestrel. Now it's on par with Scala's Colossus. memory footprint keep very high anyway  >1GB.

**Comment by kblok** [comment]
Interesting... that number of threads was my "magic number", The ASP.NET teams are basing that on the numbers of cores you have https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/CSharp/aspnetcore/setup-plaintext.sh#L3

Good job!

**Pull request merged**
