### PR TITLE
Added Simple parallelism to the Crystal server example

### PR DESCRIPTION
**Pull request by aurimasniekis**

### CODE REVIEW

**Comment by costajob** [comment]
Thanks, elegant and straight!
I will update code slightly to be more concise and update benchmarks.

**Comment by costajob** [comment]
Tested your implementation: it seems that spawning multiple process does not grant parallelism.
Each process simply share the same CPU and use a fragment of it: indeed if i spawn more than 7 processes, the exceeding ones are not used at all (0%).
There must be something in the Crystal runtime that prevent using more than one core...
Throughput is identical to original implementation, so i revert to it: it is more simple.
I suspect we've to wait for real parallelism through fibers ;)
Thanks nonetheless!

**Comment by aurimasniekis** [comment]
Hi, It's not that crystal does not utilize cpus but the OSX kernel does not want to balance sockets correctly. Run the same script in the linux os and u will see the difference

**Comment by costajob** [comment]
Yeah, i suspect that OSX does not support [SO_REUSEPORT](https://lwn.net/Articles/542629/)
Said that i cannot afford porting all of the benchmarks on a different platform right now. 
I suspect we'll have to wait for an official Crystal pre-forking library (like the Node one), or for parallelism support via fibers.
Thanks

**Comment by aurimasniekis** [comment]
No, it has nothing to do with SO_REUSEPORT thing because I create a socket server and then starts listening on multiple processes from same opened FD it's like ruby unicorn server. But on OSX kernel does not really want to balance the load and prefers some processes more often than compared to Linux where all processes have received almost equal part of requests.

**Comment by aurimasniekis** [comment]
Here is single process vs 4 processes on my machine
```
➜  forker git:(master) ✗ wrk -t 4 -c 100 -d30s --timeout 2000 http://127.0.0.1:9292
Running 30s test @ http://127.0.0.1:9292
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.72ms   11.56ms 136.73ms   89.62%
    Req/Sec    15.63k     5.17k   43.14k    74.24%
  1866577 requests in 30.10s, 178.01MB read
Requests/sec:  62017.14
Transfer/sec:      5.91MB
➜  forker git:(master) ✗ wrk -t 4 -c 100 -d30s --timeout 2000 http://127.0.0.1:9292
Running 30s test @ http://127.0.0.1:9292
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.36ms  535.11us  13.42ms   86.58%
    Req/Sec     7.47k   384.21     8.54k    68.58%
  891618 requests in 30.02s, 85.03MB read
Requests/sec:  29703.67
Transfer/sec:      2.83MB
```

**Comment by costajob** [comment]
> But on OSX kernel does not really want to balance the load and prefers some processes more often than compared to Linux where all processes have received almost equal part of requests.
Then why both Ruby+Puma, Python+GUnicorn and Node Cluster all are balanced the right way when spawning multiple processes?

**Comment by aurimasniekis** [comment]
Puma is not fork based server it's threaded. I don't know about the others. Also, this is simple fork script with no management and etc. Normally if a process doesn't handle request u kill it and replace it with a new one. But it doesn't matter I just wanted to make bit fair benchmark.

**Comment by costajob** [comment]
Check Puma codebase: it's threaded, but since MRI has GIL, it also supports pre-forking for parallelism (link Unicorn and Passenger does). 
I know it is a simple pre-forking model for Crystal, but as it is, it's not working on OSX, while other mentioned ones do.

**Pull request merged**
